name: Docker Image CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'
  schedule:
      - cron: '0 0 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@main
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/microsoft-edge-stable
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@master
        with:
          context:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

